# Generated by Django 5.2.7 on 2026-01-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, help_text='Table of contents structure'),
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file directly', null=True, upload_to='materials/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path relative to MATERIALS_ROOT (for scanned files)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'Audio MP3'), ('wav', 'Audio WAV'), ('video', 'Video'), ('image', 'Image'), ('exe', 'Aplicação .exe'), ('zip', 'Arquivo ZIP'), ('doc', 'Documento Word'), ('xls', 'Planilha Excel'), ('ppt', 'Apresentação PowerPoint'), ('other', 'Outro')], default='other', max_length=10),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level_number', models.IntegerField(default=1, help_text='Level order (1, 2, 3...)')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.course')),
            ],
            options={
                'ordering': ['level_number', 'order'],
                'unique_together': {('course', 'level_number')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level this material belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.level'),
        ),
    ]
